---
driver:
  name: vagrant

platforms:
- name: windows-2012R2
  driver_config:
    box: mwrock/Windows2012R2
    communicator: winrm
    vm_hostname: false
    customize:
      memory: 1024
  transport:
    name: winrm
    password: vagrant
    username: vagrant

provisioner:
  name: chef_zero

suites:
  - name: default
    run_list:
      - recipe[sysmon::default]
    attributes:
